# Generated by Django 3.2.3 on 2021-05-27 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_auto_20210523_1321'),
        ('patients', '0003_patients_doctor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HIVStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antibody_test_result', models.CharField(max_length=50, null=True)),
                ('antigen_test_result', models.CharField(max_length=50, null=True)),
                ('nucleic_acid_test_result', models.IntegerField(null=True)),
                ('cd4_t_test_result', models.CharField(max_length=50, null=True)),
                ('drug_resistant_type', models.CharField(max_length=50, null=True)),
                ('symptoms', models.TextField(null=True)),
                ('hiv_test', models.IntegerField(null=True)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctors')),
                ('patient_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hiv_stats', to='patients.patients')),
            ],
        ),
    ]
