# Generated by Django 3.2.3 on 2021-05-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiv_stats', '0002_hivstats_patient_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hivstats',
            name='doctor_uuid',
            field=models.CharField(default='test', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
