# Generated by Django 3.2.3 on 2021-05-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0002_alter_medication_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='doctor_uuid',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
