# Generated by Django 3.2.3 on 2021-05-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0004_medication_patient_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='doctor_uuid',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='patient_uuid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
