# Generated by Django 3.2.3 on 2021-05-23 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import doctors.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='password',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='username',
        ),
        migrations.AddField(
            model_name='doctors',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='uuid',
            field=models.CharField(default=doctors.models.hex_uuid, editable=False, max_length=32, unique=True),
        ),
    ]
