# Generated by Django 3.2.3 on 2021-05-26 06:05

from django.db import migrations, models
import doctors.models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20210523_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=doctors.models.hex_uuid, editable=False, max_length=32, unique=True)),
                ('drid', models.CharField(editable=False, max_length=32)),
                ('patient_name', models.CharField(editable=False, max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('date_submit', models.CharField(editable=False, max_length=32)),
                ('date_end', models.CharField(editable=False, max_length=32)),
                ('mon', models.BooleanField(default=False)),
                ('tue', models.BooleanField(default=False)),
                ('wed', models.BooleanField(default=False)),
                ('thu', models.BooleanField(default=False)),
                ('fri', models.BooleanField(default=False)),
                ('sat', models.BooleanField(default=False)),
                ('sun', models.BooleanField(default=False)),
                ('phone_number', models.CharField(editable=False, max_length=20)),
                ('reminder_freq', models.CharField(editable=False, max_length=20)),
            ],
        ),
    ]
