# Generated by Django 3.2.3 on 2021-05-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_auto_20210527_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorschedules',
            old_name='date_end',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='doctorschedules',
            old_name='date_submit',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='doctorschedules',
            name='active',
        ),
        migrations.RemoveField(
            model_name='doctorschedules',
            name='reminder_freq',
        ),
        migrations.AddField(
            model_name='doctorschedules',
            name='time',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
