# Generated by Django 3.2.3 on 2021-05-16 16:32

from django.db import migrations, models
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='uuid',
            field=models.CharField(default=patients.models.hex_uuid, editable=False, max_length=32, unique=True),
        ),
    ]
