# Generated by Django 3.2.3 on 2021-05-16 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0002_alter_patients_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='doctor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctors'),
        ),
    ]
