# Generated by Django 3.2.3 on 2021-05-26 02:05

from django.db import migrations, models
import django.db.models.deletion
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20210523_1321'),
        ('patients', '0003_patients_doctor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=patients.models.hex_uuid, editable=False, max_length=32, unique=True)),
                ('patientNote', models.TextField(editable=False)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctors')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patients')),
            ],
        ),
    ]
