# Generated by Django 3.2.3 on 2021-05-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patientchart'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientchart',
            name='patient_uuid',
            field=models.CharField(default='', max_length=32),
        ),
    ]
