# Generated by Django 3.2.3 on 2021-05-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patientchart_patient_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='height',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
