# Generated by Django 3.2.3 on 2021-05-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patients_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientchart',
            name='patientNote',
            field=models.TextField(),
        ),
    ]
