# Generated by Django 3.2.3 on 2021-05-26 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctorschedules'),
        ('patients', '0009_alter_patientchart_patient_uuid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientChart',
            new_name='PatientChartModel',
        ),
    ]
