# Generated by Django 3.2.3 on 2021-05-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_alter_patientchartmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientchartmodel',
            name='date',
            field=models.CharField(max_length=32),
        ),
    ]
